In [1]:
import torch
import torch.nn as nn

In [2]:
# 输入数据
input = torch.randn(3, 2)
print(input)
# 得到预测概率值
pred = torch.sigmoid(input)
print(pred)

tensor([[ 0.9073, -0.1115],
        [-0.3152,  0.2476],
        [-0.6324,  0.7665]])
tensor([[0.7125, 0.4722],
        [0.4219, 0.5616],
        [0.3470, 0.6828]])


In [3]:
# 目标值
target = torch.tensor([[0,1],[1,0],[0,1]], dtype=torch.float)
print(target)

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])


In [4]:
# 定义损失函数
loss = nn.BCELoss()
print(loss(pred, target))

tensor(0.7487)
