In [1]:
import torch
import torch.nn as nn

In [2]:
# 1. 目标值为顺序编码的标签
input = torch.randn(6, 8)
print(input)
# pred = torch.softmax(input, dim=1)
# print(pred)

tensor([[ 0.4868, -0.5571, -1.2625,  0.2893,  0.9801,  1.0285,  0.2732, -1.1990],
        [ 1.3742, -0.9836,  0.0595,  0.7092, -1.0625, -0.0249,  0.2948,  1.1178],
        [-2.1714,  0.0913,  0.6264, -0.3191, -0.8048, -1.0480, -0.8949, -2.1863],
        [-1.0206,  1.6731, -0.3811,  0.2700,  0.1744,  0.4522, -0.3429, -0.7843],
        [ 0.9399, -1.3688,  0.1286, -0.9186,  0.0798, -0.3657, -1.6049, -1.0458],
        [ 0.0163,  0.2917,  0.7066, -0.8480, -1.0442,  0.2152,  0.5384,  1.5344]])


In [3]:
# 目标值，6个数据的类别标签（0~7）
target = torch.tensor([1, 0, 3, 7, 5, 2])
print(target)

tensor([1, 0, 3, 7, 5, 2])


In [4]:
# 定义损失函数
loss = nn.CrossEntropyLoss()
print(loss(input, target))

tensor(2.2401)


In [5]:
# 2. 目标值为一组概率（独热编码）
input = torch.randn(6, 8)
print(input)

tensor([[-1.1606, -0.4701, -1.0154, -0.9315, -1.0243,  0.6036,  0.8287,  0.6689],
        [-0.2111, -1.3072,  0.1505,  0.3782,  0.0456,  1.0025,  0.6681, -0.9338],
        [-1.5226, -0.0982, -1.4536,  0.2299, -0.9196, -1.1490,  1.3534,  2.0105],
        [-0.4676, -0.4769,  0.6869, -1.8098, -1.7729, -0.2379, -1.4247,  0.3204],
        [-0.1522, -0.3043, -2.3508, -0.0331,  1.1099, -0.4375,  0.3470, -1.3255],
        [ 1.9397,  1.6690,  0.0186,  0.0217,  0.3819,  0.0726, -0.9913,  0.2240]])


In [6]:
target = torch.randn(6, 8).softmax(dim=1)
print(target)

tensor([[0.1811, 0.0604, 0.1849, 0.0189, 0.0730, 0.2955, 0.0672, 0.1189],
        [0.3043, 0.0449, 0.0162, 0.1640, 0.0131, 0.0881, 0.1442, 0.2253],
        [0.0195, 0.0190, 0.2347, 0.0960, 0.4172, 0.0379, 0.1333, 0.0425],
        [0.2623, 0.1002, 0.0505, 0.2469, 0.0851, 0.1253, 0.0370, 0.0926],
        [0.0983, 0.0367, 0.0839, 0.0168, 0.0834, 0.0183, 0.4853, 0.1773],
        [0.0786, 0.1991, 0.1164, 0.0354, 0.1042, 0.0291, 0.2798, 0.1573]])


In [7]:
loss = nn.CrossEntropyLoss()
print(loss(input, target))

tensor(2.5593)
