In [1]:
import torch
import torch.nn as nn


In [2]:
# 定义一个全链接层
linear = nn.Linear(5,2)


In [4]:
# 1. 常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [5]:
nn.init.ones_(linear.bias)
print(linear.bias)

Parameter containing:
tensor([1., 1.], requires_grad=True)


In [6]:
nn.init.constant_(linear.weight, 10)

Parameter containing:
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]], requires_grad=True)

In [7]:
# 秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [8]:
# 正态分布初始化
nn.init.normal_(linear.weight, mean=0, std=1)

Parameter containing:
tensor([[ 0.6328, -0.7624,  0.4683,  0.2474, -1.3401],
        [-0.9195,  1.6474,  0.4362, -1.0491, -1.0541]], requires_grad=True)

In [9]:
# 均匀分布初始化
nn.init.uniform_(linear.weight, a=-1, b=1)
print(linear.weight)

Parameter containing:
tensor([[ 2.7529e-01,  5.5490e-01, -7.6420e-01, -1.5282e-01,  9.2324e-01],
        [ 1.2501e-01,  6.0708e-01,  2.3673e-01,  3.9208e-04,  7.1353e-01]],
       requires_grad=True)


In [10]:
# Xavier 初始化
nn.init.xavier_normal_(linear.weight)

Parameter containing:
tensor([[ 0.3457,  0.6121, -0.6177, -0.3873,  0.1073],
        [ 0.7427,  0.0800, -0.0490, -0.0867, -0.2174]], requires_grad=True)

In [11]:
nn.init.xavier_uniform_(linear.weight)

Parameter containing:
tensor([[-0.2517,  0.6048, -0.7264,  0.7760,  0.6672],
        [ 0.1891,  0.5339, -0.3513, -0.5108, -0.7994]], requires_grad=True)

In [13]:
# He 初始化
nn.init.kaiming_normal_(linear.weight)

Parameter containing:
tensor([[-0.7068, -1.5914,  0.5046,  1.5296, -0.8220],
        [-0.9163, -0.4872,  0.6574,  0.4074,  0.4906]], requires_grad=True)