# 一 numpy
## numpy的特性
### 多维性


In [1]:
import numpy as np
from fontTools.misc.symfont import printGreenPen


In [6]:
arr = np.array([[1, 2, 3, 4, 5],[1,2,3,4,5]])
print(arr)
print(arr.ndim)


[[1 2 3 4 5]
 [1 2 3 4 5]]
2


### 同质性



In [7]:
arr = np.array([1,'hello'])
print(arr)

['1' 'hello']


### ndarray数组的创建

In [8]:
arr = np.arange(1,10,3)
print(arr)

[1 4 7]


In [9]:
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
arr = np.logspace(0,4,3,base = 2)
print(arr)

[ 1.  4. 16.]


### 特殊矩阵的构造

In [12]:
arr = np.eye(3,dtype=int)
print( arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [13]:
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [15]:
arr = np.random.rand(2,3)
print( arr)


[[0.27047458 0.30077682 0.54332433]
 [0.74006607 0.82334122 0.92374865]]


In [16]:
arr = np.random.uniform(3,6,size=(2,3))
print( arr)

[[5.6586894  4.49568826 5.36013391]
 [3.63239845 5.82700895 4.46158575]]


In [18]:
arr = np.random.randint(3,30,size=(2,3))
print( arr)

[[ 7 19 23]
 [13  8 25]]


In [23]:
# 正态分布
arr = np.random.rand(2,3)
print( arr)

[[0.80268982 0.1195845  0.65970066]
 [0.4644935  0.9716444  0.54286527]]


In [24]:
arr = np.random.randint(1,100,20)
print( arr)

[ 3 54  6 24 52 73 89 92  4 53 50 17 59 56 13 64  2 86 54 96]


In [31]:
print(arr[10])
print(arr[10:])
print(arr[:10])
print(arr[:])
print(arr[2:5])
print(arr[arr>10])

50
[50 17 59 56 13 64  2 86 54 96]
[ 3 54  6 24 52 73 89 92  4 53]
[ 3 54  6 24 52 73 89 92  4 53 50 17 59 56 13 64  2 86 54 96]
[ 6 24 52]
[54 24 52 73 89 92 53 50 17 59 56 13 64 86 54 96]
