In [1]:
from cmath import log10
from traceback import print_tb

import numpy as np

In [16]:
x = np.array([5,2,8])
print(x)
print(x.shape)

[5 2 8]
(3,)


In [5]:
print(x.T)
print(x.T.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [6]:
y = np.array([1,6,7])
print(x + y)

[[ 2  8 10]]


In [7]:
print(x * 3)

[[3 6 9]]


In [8]:
print(x * y)

[[ 1 12 21]]


In [9]:
print(x.dot(y))

[34]


In [17]:
#计算范数
l0_norm = np.linalg.norm(x,ord=0)
print(l0_norm)

3.0


In [18]:
l0_norm = np.linalg.norm(x,ord=1)
print(l0_norm)

15.0


In [19]:
l0_norm = np.linalg.norm(x,ord=2)
print(l0_norm)

9.643650760992955
