In [2]:
from traceback import print_tb

import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,3,7],[5,0,2]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [3]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
print(A + B)

[[ 2  5 10]
 [ 9  5  8]]


In [5]:
print(A * B)

[[ 1  6 21]
 [20  0 12]]


In [10]:
print(A @ B.T)

[[28 11]
 [61 32]]


In [11]:
C = np.array([[1,2],[3,5]])
C_inv = np.linalg.inv(C)
print(C_inv)

[[-5.  2.]
 [ 3. -1.]]


In [13]:
#向量化
(A.flatten())

array([1, 2, 3, 4, 5, 6])

In [16]:
#矩阵内积
print(np.sum(A * B))
print(np.dot(A.flatten(), B.flatten()))

60
60


In [17]:
#哈达码积
np.multiply(A, B)


array([[ 1,  6, 21],
       [20,  0, 12]])

In [19]:
# 克罗内克积
np.kron(A, B)

array([[ 1,  3,  7,  2,  6, 14,  3,  9, 21],
       [ 5,  0,  2, 10,  0,  4, 15,  0,  6],
       [ 4, 12, 28,  5, 15, 35,  6, 18, 42],
       [20,  0,  8, 25,  0, 10, 30,  0, 12]])

In [22]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)
print(tensor.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [23]:
# 计算梯度
f = np.array([1,2,4,7,11,16])
np.gradient(f)


array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])

In [25]:
print(A)
print(np.gradient(A))

[[1 2 3]
 [4 5 6]]
(array([[3., 3., 3.],
       [3., 3., 3.]]), array([[1., 1., 1.],
       [1., 1., 1.]]))
