In [1]:
from traceback import print_tb

import numpy as np

In [3]:
a = np.random.rand(5)
b = np.random.rand(2,3)
c = np.random.randint(0,100,size = [2,3])
print(c)


[[73 63 95]
 [58 59 61]]


In [5]:
# 随机生成复合标准正态分布的数据
d = np.random.randn(2,5)
print(d)

[[-1.53375137 -0.9098787  -0.30844231 -0.42624651  2.09096463]
 [-1.93167228  0.31126119  0.16377302  0.66578481 -0.94532932]]
