In [1]:
import numpy as np
import  torch

# 张量类型转换


In [2]:
tensor1 = torch.tensor([1,2,3])
print(tensor1.dtype)

torch.int64


In [3]:
tensor1 = tensor1.type(torch.float64)
print(tensor1.dtype)

torch.float64


In [4]:
tensor1 = tensor1.half()
print(tensor1.dtype)

torch.float16


In [5]:
print(tensor1)

tensor([1., 2., 3.], dtype=torch.float16)


In [6]:
tensor1 = tensor1.to(torch.complex64)
print(tensor1, tensor1.dtype)

tensor([1.+0.j, 2.+0.j, 3.+0.j]) torch.complex64


# Tensor 和 ndarray 的转换


In [7]:
np.set_printoptions(precision=6)
torch.set_printoptions(precision=6)

# 1. tensor → ndarray
tensor1 = torch.rand(3, 2)
print(tensor1)

tensor([[0.338412, 0.396524],
        [0.544435, 0.907458],
        [0.481480, 0.023717]])


In [8]:
ndarray1 = tensor1.numpy()
print(ndarray1)

[[0.338412 0.396524]
 [0.544435 0.907458]
 [0.48148  0.023717]]


In [9]:
tensor1[:, 0] = 10
print(tensor1)
print(ndarray1)

tensor([[10.000000,  0.396524],
        [10.000000,  0.907458],
        [10.000000,  0.023717]])
[[10.        0.396524]
 [10.        0.907458]
 [10.        0.023717]]


In [10]:
# 使用copy方法避免共享内存
ndarray2 = tensor1.numpy().copy()
print(ndarray2)

[[10.        0.396524]
 [10.        0.907458]
 [10.        0.023717]]


In [11]:
tensor1[:, 0] = 5
print(tensor1)
print(ndarray1)
print(ndarray2)

tensor([[5.000000, 0.396524],
        [5.000000, 0.907458],
        [5.000000, 0.023717]])
[[5.       0.396524]
 [5.       0.907458]
 [5.       0.023717]]
[[10.        0.396524]
 [10.        0.907458]
 [10.        0.023717]]


In [12]:
# 2. ndarray → tensor
ndarray1 = np.random.randn(3, 2)
tensor1 = torch.from_numpy(ndarray1)
print(tensor1)
print(ndarray1)

tensor([[-1.423315, -0.302627],
        [-0.456821, -1.583842],
        [ 1.941017,  2.037826]], dtype=torch.float64)
[[-1.423315 -0.302627]
 [-0.456821 -1.583842]
 [ 1.941017  2.037826]]


In [13]:
ndarray1[:, 0] = 5
print(tensor1)
print(ndarray1)

tensor([[ 5.000000, -0.302627],
        [ 5.000000, -1.583842],
        [ 5.000000,  2.037826]], dtype=torch.float64)
[[ 5.       -0.302627]
 [ 5.       -1.583842]
 [ 5.        2.037826]]


In [14]:
# 使用copy方法避免内存共享
tensor2 = torch.from_numpy(ndarray1.copy())
ndarray1[:, 0] = 7
print(ndarray1)
print(tensor1)
print(tensor2)

[[ 7.       -0.302627]
 [ 7.       -1.583842]
 [ 7.        2.037826]]
tensor([[ 7.000000, -0.302627],
        [ 7.000000, -1.583842],
        [ 7.000000,  2.037826]], dtype=torch.float64)
tensor([[ 5.000000, -0.302627],
        [ 5.000000, -1.583842],
        [ 5.000000,  2.037826]], dtype=torch.float64)


In [15]:
# 使用tensor方法直接转换成Tensor
ndarray1 = np.random.randn(3, 2)
tensor1 = torch.tensor(ndarray1)
print(tensor1)
print(ndarray1)

tensor([[-0.876031, -0.022571],
        [ 1.023388,  0.079681],
        [-0.887908, -0.779752]], dtype=torch.float64)
[[-0.876031 -0.022571]
 [ 1.023388  0.079681]
 [-0.887908 -0.779752]]


In [16]:
ndarray1[:, 0] = 5
print(tensor1)
print(ndarray1)

tensor([[-0.876031, -0.022571],
        [ 1.023388,  0.079681],
        [-0.887908, -0.779752]], dtype=torch.float64)
[[ 5.       -0.022571]
 [ 5.        0.079681]
 [ 5.       -0.779752]]


In [17]:
# 张量与标量的转换
tensor1 = torch.tensor(10)
print(tensor1)

tensor(10)


In [18]:
print( tensor1.item() )

10


In [19]:
tensor1 = torch.tensor([[10]])
print(tensor1)
print( tensor1.item() )

tensor([[10]])
10
