In [1]:
import torch

In [2]:
# 1. 四则运算
tensor1 = torch.randint(low=0, high=10, size=(2,3))
print(tensor1)

tensor([[0, 8, 5],
        [7, 3, 2]])


In [3]:
print(tensor1 + 10)

tensor([[10, 18, 15],
        [17, 13, 12]])


In [4]:
print(tensor1.add(10))

tensor([[10, 18, 15],
        [17, 13, 12]])


In [5]:
print(tensor1)

tensor([[0, 8, 5],
        [7, 3, 2]])


In [6]:
print(tensor1.add_(10))
print(tensor1)

tensor([[10, 18, 15],
        [17, 13, 12]])
tensor([[10, 18, 15],
        [17, 13, 12]])


In [7]:
print(tensor1.sub_(10))

tensor([[0, 8, 5],
        [7, 3, 2]])


In [8]:
# 幂函数
print(tensor1 ** 2)

tensor([[ 0, 64, 25],
        [49,  9,  4]])


In [9]:
print(tensor1.pow(2))
print(tensor1)

tensor([[ 0, 64, 25],
        [49,  9,  4]])
tensor([[0, 8, 5],
        [7, 3, 2]])


In [10]:
print(tensor1.pow_(2))
print(tensor1)

tensor([[ 0, 64, 25],
        [49,  9,  4]])
tensor([[ 0, 64, 25],
        [49,  9,  4]])


In [11]:
print(tensor1.sqrt())

tensor([[0., 8., 5.],
        [7., 3., 2.]])


In [12]:
print(tensor1)

tensor([[ 0, 64, 25],
        [49,  9,  4]])


In [13]:
tensor1 = tensor1.float()
print(tensor1.sqrt_())
print(tensor1)

tensor([[0., 8., 5.],
        [7., 3., 2.]])
tensor([[0., 8., 5.],
        [7., 3., 2.]])


In [14]:
tensor1 = torch.tensor([1.0, 2, 3])
print(tensor1)
print(2.7182818 ** tensor1)

tensor([1., 2., 3.])
tensor([ 2.7183,  7.3891, 20.0855])


In [15]:
print(tensor1.exp())

tensor([ 2.7183,  7.3891, 20.0855])


In [16]:
print(tensor1)
print(tensor1.exp_())
print(tensor1)

tensor([1., 2., 3.])
tensor([ 2.7183,  7.3891, 20.0855])
tensor([ 2.7183,  7.3891, 20.0855])


In [17]:
# 计算张量的哈达玛积
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[1, 2], [3, 4]])
print(tensor1 + tensor2)
print(tensor1 * tensor2)

tensor([[2, 4],
        [6, 8]])
tensor([[ 1,  4],
        [ 9, 16]])


In [18]:
print(tensor1.mul(tensor2))

tensor([[ 1,  4],
        [ 9, 16]])


In [19]:
# 张量乘法
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(tensor1 @ tensor2)

tensor([[22, 28],
        [49, 64]])


In [20]:
print(tensor1.matmul(tensor2))

tensor([[22, 28],
        [49, 64]])


In [21]:
print(tensor1.mm(tensor2))

tensor([[22, 28],
        [49, 64]])


In [22]:
tensor1 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[6, 5, 4], [3, 2, 1]]])
tensor2 = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[6, 5], [4, 3], [2, 1]]])
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))

tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])
tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])


In [23]:
# print(tensor1.mm(tensor2))
tensor1 = torch.randn(4, 2, 2, 3)
tensor2 = torch.randn(1, 1, 3, 5)
tensor3 = tensor1 @ tensor2
print(tensor3.shape)

torch.Size([4, 2, 2, 5])


In [25]:
# 验证内存的共享和节省内存
X = torch.randint(1, 10, (3, 2, 4))
print(X)
print(id(X))

tensor([[[2, 4, 1, 7],
         [7, 1, 7, 8]],

        [[3, 2, 4, 9],
         [8, 4, 9, 3]],

        [[5, 6, 6, 5],
         [2, 3, 3, 4]]])
4552964032


In [28]:
# X = X + 10
X += 10
print(X)
print(id(X))

tensor([[[32, 34, 31, 37],
         [37, 31, 37, 38]],

        [[33, 32, 34, 39],
         [38, 34, 39, 33]],

        [[35, 36, 36, 35],
         [32, 33, 33, 34]]])
4552964032


In [29]:
X = torch.randint(1, 10, (3, 2, 4))
Y = torch.randint(1, 10, (3, 4, 1))
print(X.shape)
print(id(X))
print(X)
print(Y)
print(X @ Y)
# X = X @ Y
# X @= Y
X[:] = X @ Y
print(X.shape)
print(X)
print(id(X))

torch.Size([3, 2, 4])
4552989968
tensor([[[7, 7, 6, 9],
         [1, 5, 1, 6]],

        [[1, 5, 8, 1],
         [1, 5, 5, 3]],

        [[6, 6, 2, 5],
         [2, 2, 7, 2]]])
tensor([[[4],
         [3],
         [8],
         [8]],

        [[7],
         [6],
         [1],
         [2]],

        [[7],
         [7],
         [3],
         [5]]])
tensor([[[169],
         [ 75]],

        [[ 47],
         [ 48]],

        [[115],
         [ 59]]])
torch.Size([3, 2, 4])
tensor([[[169, 169, 169, 169],
         [ 75,  75,  75,  75]],

        [[ 47,  47,  47,  47],
         [ 48,  48,  48,  48]],

        [[115, 115, 115, 115],
         [ 59,  59,  59,  59]]])
4552989968
