In [1]:
import torch

In [2]:
tensor1 = torch.randint(1, 10, (3, 2, 4)).float()
print(tensor1)

tensor([[[4., 6., 8., 6.],
         [5., 1., 4., 9.]],

        [[5., 8., 5., 2.],
         [1., 1., 6., 7.]],

        [[5., 2., 4., 7.],
         [5., 2., 4., 7.]]])


In [3]:
# sum 求和
print(tensor1.sum())

tensor(114.)


In [4]:
print(tensor1.sum(dim=2))

tensor([[24., 19.],
        [20., 15.],
        [18., 18.]])


In [5]:
# mean 求均值
print(tensor1.mean())

tensor(4.7500)


In [6]:
print(tensor1.mean(dim=2))

tensor([[6.0000, 4.7500],
        [5.0000, 3.7500],
        [4.5000, 4.5000]])


In [7]:
# std 求标准方差
print(tensor1.std())

tensor(2.3452)


In [8]:
# max、min求最大最小值
print(tensor1.max())

tensor(9.)


In [9]:
print(tensor1.min(dim=2))

torch.return_types.min(
values=tensor([[4., 1.],
        [2., 1.],
        [2., 2.]]),
indices=tensor([[0, 1],
        [3, 0],
        [1, 1]]))


In [10]:
print(tensor1.argmax())

tensor(7)


In [11]:
# 去重
print(tensor1.unique())

tensor([1., 2., 4., 5., 6., 7., 8., 9.])


In [12]:
# 排序
print(tensor1.sort())

torch.return_types.sort(
values=tensor([[[4., 6., 6., 8.],
         [1., 4., 5., 9.]],

        [[2., 5., 5., 8.],
         [1., 1., 6., 7.]],

        [[2., 4., 5., 7.],
         [2., 4., 5., 7.]]]),
indices=tensor([[[0, 1, 3, 2],
         [1, 2, 0, 3]],

        [[3, 0, 2, 1],
         [0, 1, 2, 3]],

        [[1, 2, 0, 3],
         [1, 2, 0, 3]]]))
