In [1]:
import torch

In [2]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1)

tensor([[[8, 2, 5, 9],
         [2, 3, 3, 8],
         [4, 5, 4, 8],
         [6, 6, 4, 8],
         [5, 5, 6, 6]],

        [[3, 5, 8, 7],
         [6, 2, 7, 2],
         [1, 6, 8, 8],
         [9, 6, 2, 2],
         [5, 1, 2, 8]],

        [[5, 5, 1, 4],
         [5, 3, 3, 2],
         [5, 7, 6, 8],
         [2, 6, 7, 9],
         [1, 7, 4, 1]]])


In [3]:
# 1. 简单索引
print(tensor1[2, 1, 3])

tensor(2)


In [4]:
print(tensor1[2, 3])

tensor([2, 6, 7, 9])


In [5]:
print(tensor1[1])

tensor([[3, 5, 8, 7],
        [6, 2, 7, 2],
        [1, 6, 8, 8],
        [9, 6, 2, 2],
        [5, 1, 2, 8]])


In [7]:
print(tensor1[:, 3])

tensor([[6, 6, 4, 8],
        [9, 6, 2, 2],
        [2, 6, 7, 9]])


In [9]:
# 2. 范围索引
print(tensor1[1:])

tensor([[[3, 5, 8, 7],
         [6, 2, 7, 2],
         [1, 6, 8, 8],
         [9, 6, 2, 2],
         [5, 1, 2, 8]],

        [[5, 5, 1, 4],
         [5, 3, 3, 2],
         [5, 7, 6, 8],
         [2, 6, 7, 9],
         [1, 7, 4, 1]]])


In [10]:
print(tensor1[-1:, 1:4, 0:3])

tensor([[[5, 3, 3],
         [5, 7, 6],
         [2, 6, 7]]])


In [11]:
print(tensor1[-1:, 1:4:2, 0:3:2])

tensor([[[5, 3],
         [2, 7]]])


In [12]:
# print(tensor1[-1:, 4:1:-2, 0:3:2])
print(tensor1[-1:, -4:-1:2, 0:3:2])

tensor([[[5, 3],
         [2, 7]]])


In [25]:
# 3. 列表索引
print(tensor1[[0, 1], [3, 2]])

tensor([[6, 6, 4, 8],
        [1, 6, 8, 8]])


In [26]:
print(tensor1[[0, 1], [3, 2], [2, 3]])

tensor([4, 8])


In [27]:
print(tensor1[[[0], [1]], [1, 2]])

tensor([[[2, 3, 3, 8],
         [4, 5, 4, 8]],

        [[6, 2, 7, 2],
         [1, 6, 8, 8]]])


In [37]:
# 4. 布尔索引
# 4.1 选取符合条件的行：首元素大于5
mask = tensor1[:, :, 0] > 5
print(mask)

tensor([[ True, False, False,  True, False],
        [False,  True, False,  True, False],
        [False, False, False, False, False]])


In [38]:
print(tensor1[mask])

tensor([[8, 2, 5, 9],
        [6, 6, 4, 8],
        [6, 2, 7, 2],
        [9, 6, 2, 2]])


In [39]:
# 4.2 选取符合条件的列：第二个元素大于5
mask = tensor1[:, 1, :] > 5
print(mask)

tensor([[False, False, False,  True],
        [ True, False,  True, False],
        [False, False, False, False]])


In [40]:
# print(tensor1[mask])
tensor2 = tensor1.mT
print(tensor2)

tensor([[[8, 2, 4, 6, 5],
         [2, 3, 5, 6, 5],
         [5, 3, 4, 4, 6],
         [9, 8, 8, 8, 6]],

        [[3, 6, 1, 9, 5],
         [5, 2, 6, 6, 1],
         [8, 7, 8, 2, 2],
         [7, 2, 8, 2, 8]],

        [[5, 5, 5, 2, 1],
         [5, 3, 7, 6, 7],
         [1, 3, 6, 7, 4],
         [4, 2, 8, 9, 1]]])


In [41]:
# 将mask应用到tensor2上，形状匹配前两个维度
print(tensor2[mask].mT)

tensor([[9, 3, 8],
        [8, 6, 7],
        [8, 1, 8],
        [8, 9, 2],
        [6, 5, 2]])


In [42]:
# 4.3 选取符合条件的矩阵: 元素（1,2）>5
mask = tensor1[:, 1, 2] > 5
print(mask)

tensor([False,  True, False])


In [43]:
print(tensor1[mask])

tensor([[[3, 5, 8, 7],
         [6, 2, 7, 2],
         [1, 6, 8, 8],
         [9, 6, 2, 2],
         [5, 1, 2, 8]]])


In [44]:
mask = tensor1 > 5
print(mask)

tensor([[[ True, False, False,  True],
         [False, False, False,  True],
         [False, False, False,  True],
         [ True,  True, False,  True],
         [False, False,  True,  True]],

        [[False, False,  True,  True],
         [ True, False,  True, False],
         [False,  True,  True,  True],
         [ True,  True, False, False],
         [False, False, False,  True]],

        [[False, False, False, False],
         [False, False, False, False],
         [False,  True,  True,  True],
         [False,  True,  True,  True],
         [False,  True, False, False]]])


In [45]:
print(tensor1[mask])

tensor([8, 9, 8, 8, 6, 6, 8, 6, 6, 8, 7, 6, 7, 6, 8, 8, 9, 6, 8, 7, 6, 8, 6, 7,
        9, 7])
