In [1]:
import torch

In [25]:
tensor1 = torch.randint(1, 10, (2, 3, 6))
print(tensor1)

tensor([[[5, 4, 2, 5, 9, 4],
         [5, 8, 8, 3, 5, 4],
         [8, 7, 8, 8, 7, 5]],

        [[7, 6, 7, 4, 5, 5],
         [1, 9, 6, 2, 6, 3],
         [2, 5, 5, 8, 7, 7]]])


6.8.1 交换维度

In [26]:
# 1. 交换两个维度
print(tensor1.transpose(0, 2))

tensor([[[5, 7],
         [5, 1],
         [8, 2]],

        [[4, 6],
         [8, 9],
         [7, 5]],

        [[2, 7],
         [8, 6],
         [8, 5]],

        [[5, 4],
         [3, 2],
         [8, 8]],

        [[9, 5],
         [5, 6],
         [7, 7]],

        [[4, 5],
         [4, 3],
         [5, 7]]])


In [27]:
# 2. 重新排列多个维度
print(tensor1.permute(0, 2, 1))

tensor([[[5, 5, 8],
         [4, 8, 7],
         [2, 8, 8],
         [5, 3, 8],
         [9, 5, 7],
         [4, 4, 5]],

        [[7, 1, 2],
         [6, 9, 5],
         [7, 6, 5],
         [4, 2, 8],
         [5, 6, 7],
         [5, 3, 7]]])


6.8.2 调整形状

In [38]:
# 1. reshape
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1.shape)
print(tensor1)

torch.Size([3, 5, 4])
tensor([[[6, 5, 9, 1],
         [1, 1, 5, 3],
         [5, 4, 4, 2],
         [7, 3, 7, 5],
         [6, 3, 1, 8]],

        [[7, 7, 4, 1],
         [1, 3, 2, 9],
         [5, 8, 6, 3],
         [1, 3, 5, 2],
         [6, 8, 4, 2]],

        [[2, 5, 1, 8],
         [2, 8, 1, 9],
         [8, 4, 2, 4],
         [1, 7, 7, 3],
         [1, 3, 4, 5]]])


In [39]:
print(tensor1.reshape(6, 10))

tensor([[6, 5, 9, 1, 1, 1, 5, 3, 5, 4],
        [4, 2, 7, 3, 7, 5, 6, 3, 1, 8],
        [7, 7, 4, 1, 1, 3, 2, 9, 5, 8],
        [6, 3, 1, 3, 5, 2, 6, 8, 4, 2],
        [2, 5, 1, 8, 2, 8, 1, 9, 8, 4],
        [2, 4, 1, 7, 7, 3, 1, 3, 4, 5]])


In [40]:
print(tensor1.reshape(3, -1))

tensor([[6, 5, 9, 1, 1, 1, 5, 3, 5, 4, 4, 2, 7, 3, 7, 5, 6, 3, 1, 8],
        [7, 7, 4, 1, 1, 3, 2, 9, 5, 8, 6, 3, 1, 3, 5, 2, 6, 8, 4, 2],
        [2, 5, 1, 8, 2, 8, 1, 9, 8, 4, 2, 4, 1, 7, 7, 3, 1, 3, 4, 5]])


In [41]:
print(tensor1.reshape(-1))

tensor([6, 5, 9, 1, 1, 1, 5, 3, 5, 4, 4, 2, 7, 3, 7, 5, 6, 3, 1, 8, 7, 7, 4, 1,
        1, 3, 2, 9, 5, 8, 6, 3, 1, 3, 5, 2, 6, 8, 4, 2, 2, 5, 1, 8, 2, 8, 1, 9,
        8, 4, 2, 4, 1, 7, 7, 3, 1, 3, 4, 5])


In [42]:
# 2. view
print(tensor1.is_contiguous())

True


In [43]:
print(tensor1.view(-1, 10))

tensor([[6, 5, 9, 1, 1, 1, 5, 3, 5, 4],
        [4, 2, 7, 3, 7, 5, 6, 3, 1, 8],
        [7, 7, 4, 1, 1, 3, 2, 9, 5, 8],
        [6, 3, 1, 3, 5, 2, 6, 8, 4, 2],
        [2, 5, 1, 8, 2, 8, 1, 9, 8, 4],
        [2, 4, 1, 7, 7, 3, 1, 3, 4, 5]])


In [44]:
print(tensor1.shape)

torch.Size([3, 5, 4])


In [45]:
# 对张量进行转置操作，让内存空间不连续
tensor1 = tensor1.permute(2,1,0)
print(tensor1.shape)

torch.Size([4, 5, 3])


In [46]:
print(tensor1.is_contiguous())

False


In [47]:
print(tensor1.contiguous().view(-1, 10))

tensor([[6, 7, 2, 1, 1, 2, 5, 5, 8, 7],
        [1, 1, 6, 6, 1, 5, 7, 5, 1, 3],
        [8, 4, 8, 4, 3, 3, 7, 3, 8, 3],
        [9, 4, 1, 5, 2, 1, 4, 6, 2, 7],
        [5, 7, 1, 4, 4, 1, 1, 8, 3, 9],
        [9, 2, 3, 4, 5, 2, 3, 8, 2, 5]])


6.8.3 增加或删除维度

In [48]:
# 1. 增加维度
tensor1 = torch.tensor([1, 2, 3])
print(tensor1)

tensor([1, 2, 3])


In [49]:
# 在 0 维上增加一个维度，1×3
print(tensor1.unsqueeze(dim=0))

tensor([[1, 2, 3]])


In [50]:
# 在 1 维上增加一个维度，3×1
print(tensor1.unsqueeze(dim=-1))
print(tensor1)

tensor([[1],
        [2],
        [3]])
tensor([1, 2, 3])


In [51]:
print(tensor1.unsqueeze_(dim=-2))
print(tensor1)

tensor([[1, 2, 3]])
tensor([[1, 2, 3]])


In [52]:
# 2. 减少维度
print(tensor1.squeeze(dim=0))

tensor([1, 2, 3])


6.9 张量拼接操作

In [53]:
# 1. 拼接
tensor1 = torch.randint(1, 10, (2, 2, 5))
tensor2 = torch.randint(1, 10, (2, 3, 5))
print(tensor1)
print(tensor2)

tensor([[[4, 7, 5, 2, 7],
         [9, 6, 2, 7, 8]],

        [[9, 4, 2, 2, 6],
         [1, 6, 8, 7, 2]]])
tensor([[[9, 2, 9, 9, 8],
         [6, 9, 3, 2, 3],
         [5, 5, 1, 3, 3]],

        [[3, 6, 3, 1, 2],
         [3, 4, 4, 3, 9],
         [1, 8, 2, 2, 4]]])


In [54]:
print(torch.cat((tensor1, tensor2), dim=1))

tensor([[[4, 7, 5, 2, 7],
         [9, 6, 2, 7, 8],
         [9, 2, 9, 9, 8],
         [6, 9, 3, 2, 3],
         [5, 5, 1, 3, 3]],

        [[9, 4, 2, 2, 6],
         [1, 6, 8, 7, 2],
         [3, 6, 3, 1, 2],
         [3, 4, 4, 3, 9],
         [1, 8, 2, 2, 4]]])


In [55]:
# 2. 堆叠
tensor1 = torch.randint(1, 10, (4, 3, 5))
tensor2 = torch.randint(1, 10, (4, 3, 5))
print(tensor1)
print(tensor2)

tensor([[[1, 3, 5, 7, 5],
         [4, 3, 4, 7, 9],
         [8, 2, 9, 2, 9]],

        [[8, 6, 6, 7, 3],
         [2, 8, 9, 3, 9],
         [4, 9, 5, 6, 9]],

        [[6, 1, 1, 4, 5],
         [9, 3, 9, 7, 6],
         [7, 1, 4, 7, 6]],

        [[6, 9, 5, 8, 3],
         [2, 6, 2, 1, 2],
         [2, 5, 6, 7, 7]]])
tensor([[[3, 5, 9, 9, 5],
         [6, 2, 8, 6, 6],
         [9, 1, 7, 7, 6]],

        [[3, 9, 4, 7, 9],
         [5, 8, 9, 2, 3],
         [1, 8, 2, 2, 3]],

        [[5, 7, 9, 9, 9],
         [8, 4, 7, 2, 2],
         [1, 1, 9, 5, 1]],

        [[5, 6, 8, 2, 5],
         [9, 4, 9, 6, 3],
         [5, 4, 2, 9, 8]]])


In [56]:
tensor3 = torch.stack([tensor1, tensor2], dim=0)
print(tensor3)
print(tensor3.shape)

tensor([[[[1, 3, 5, 7, 5],
          [4, 3, 4, 7, 9],
          [8, 2, 9, 2, 9]],

         [[8, 6, 6, 7, 3],
          [2, 8, 9, 3, 9],
          [4, 9, 5, 6, 9]],

         [[6, 1, 1, 4, 5],
          [9, 3, 9, 7, 6],
          [7, 1, 4, 7, 6]],

         [[6, 9, 5, 8, 3],
          [2, 6, 2, 1, 2],
          [2, 5, 6, 7, 7]]],


        [[[3, 5, 9, 9, 5],
          [6, 2, 8, 6, 6],
          [9, 1, 7, 7, 6]],

         [[3, 9, 4, 7, 9],
          [5, 8, 9, 2, 3],
          [1, 8, 2, 2, 3]],

         [[5, 7, 9, 9, 9],
          [8, 4, 7, 2, 2],
          [1, 1, 9, 5, 1]],

         [[5, 6, 8, 2, 5],
          [9, 4, 9, 6, 3],
          [5, 4, 2, 9, 8]]]])
torch.Size([2, 4, 3, 5])


In [57]:
tensor3 = torch.stack([tensor1, tensor2], dim=3)
print(tensor3.shape)
print(tensor3)

torch.Size([4, 3, 5, 2])
tensor([[[[1, 3],
          [3, 5],
          [5, 9],
          [7, 9],
          [5, 5]],

         [[4, 6],
          [3, 2],
          [4, 8],
          [7, 6],
          [9, 6]],

         [[8, 9],
          [2, 1],
          [9, 7],
          [2, 7],
          [9, 6]]],


        [[[8, 3],
          [6, 9],
          [6, 4],
          [7, 7],
          [3, 9]],

         [[2, 5],
          [8, 8],
          [9, 9],
          [3, 2],
          [9, 3]],

         [[4, 1],
          [9, 8],
          [5, 2],
          [6, 2],
          [9, 3]]],


        [[[6, 5],
          [1, 7],
          [1, 9],
          [4, 9],
          [5, 9]],

         [[9, 8],
          [3, 4],
          [9, 7],
          [7, 2],
          [6, 2]],

         [[7, 1],
          [1, 1],
          [4, 9],
          [7, 5],
          [6, 1]]],


        [[[6, 5],
          [9, 6],
          [5, 8],
          [8, 2],
          [3, 5]],

         [[2, 9],
          [6, 4],
          [2,