In [13]:
import torch

In [14]:
# 定义数据
x = torch.tensor(10.0)
y = torch.tensor([[3.0]])
print(x)
print(y)

tensor(10.)
tensor([[3.]])


In [15]:
# 初始化参数
w = torch.rand(1, 1, requires_grad=True)
b = torch.rand(1, 1, requires_grad=True)

In [16]:
# 前向传播，得到输出
z = w * x + b
print(z)

tensor([[9.7477]], grad_fn=<AddBackward0>)


In [17]:
print(x.is_leaf)
print(w.is_leaf)
print(b.is_leaf)
print(y.is_leaf)
print(z.is_leaf)

True
True
True
True
False


In [18]:
# 设置损失函数
loss = torch.nn.MSELoss()
loss_value = loss(z, y)
print(loss_value)
print(loss_value.is_leaf)

tensor(45.5320, grad_fn=<MseLossBackward0>)
False


In [19]:
# 反向传播
loss_value.backward()

In [20]:
# 查看梯度
print(w.grad)
print(b.grad)

tensor([[134.9548]])
tensor([[13.4955]])
