In [1]:
import torch

In [2]:
x = torch.tensor(2.0, requires_grad=True)
y = x.detach()
print(x)
print(y)

tensor(2., requires_grad=True)
tensor(2.)


In [3]:
print(x.requires_grad)
print(y.requires_grad)

True
False


In [4]:
print(id(x))
print(id(y))

4388688576
4388473888


In [5]:
print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())

4805314176
4805314176


In [14]:
# print(x)
# y.zero_()
# print(x)

In [6]:
# 分别对x、y进行后续计算
z1 = x ** 2
z2 = y ** 2
print(z1)
print(z2)

tensor(4., grad_fn=<PowBackward0>)
tensor(4.)


In [7]:
print(z1.requires_grad)
print(z2.requires_grad)

True
False


In [8]:
z1.sum().backward()

In [9]:
# z2.sum().backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [10]:
x = torch.ones(2, 2, requires_grad=True)
y = x * x
print(x)
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [11]:
# 分离y
u = y.detach()
print(u)

tensor([[1., 1.],
        [1., 1.]])


In [12]:
# 让u参与新张量的计算
z = u * x

In [13]:
# 反向传播，计算所有梯度
z.sum().backward()

In [14]:
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [15]:
print(x.grad == u)

tensor([[True, True],
        [True, True]])
