In [1]:
import torch

In [2]:
# 用两组数据进行对比
x1 = torch.tensor([1.0, 2, 3], requires_grad=True)
x2 = torch.tensor([1.0, 2, 3], requires_grad=True)
print(x1)
print(x2)

tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.], requires_grad=True)


In [3]:
y1 = x1.sigmoid()
y2 = x2.sigmoid()
print(y1)
print(y2)

tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)
tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)


In [4]:
# y1.sum().backward()
# print(x1.grad)

In [5]:
# y2.sum().backward()
# print(x2.grad)

In [6]:
z1 = y1.data
z2 = y2.detach()
print(z1)
print(z2)

tensor([0.7311, 0.8808, 0.9526])
tensor([0.7311, 0.8808, 0.9526])


In [7]:
print(z1.requires_grad)
print(z2.requires_grad)

False
False


In [8]:
z1.zero_()
z2.zero_()
print(y1)
print(y2)

tensor([0., 0., 0.], grad_fn=<SigmoidBackward0>)
tensor([0., 0., 0.], grad_fn=<SigmoidBackward0>)


In [9]:
y1.sum().backward()
print(x1.grad)

tensor([0., 0., 0.])


In [10]:
y2.sum().backward()
print(x2.grad)

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [3]], which is output 0 of SigmoidBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).