In [3]:
import torch

# 张量的基本创建  按照内容创建张量

In [7]:
#传入一个标量
tensor1 = torch.tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor(10)
torch.Size([])
torch.int64


In [8]:
#传入一个数组
tensor1 = torch.tensor([1,2,3])
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([1, 2, 3])
torch.Size([3])
torch.int64


In [9]:
# 传入一个二维 nd.array
import numpy as np
tensor3 = torch.tensor(np.array([[1,2,3],[4,5,6]]))
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


# 创建指定形状的张量


In [12]:
tensor1 = torch.Tensor(3,2,4)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([3, 2, 4])
torch.float32


In [13]:
tensor2 = torch.Tensor(np.array([[1,2,3],[4,5,6]]))
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.float32


# 创建指定类型的张量


In [14]:
tensor1 = torch.IntTensor(3,2,4)
print(tensor1.dtype)
tensor2 = torch.tensor([1,2,3])
print(tensor2.dtype)


torch.int32
torch.int64


In [18]:
tensor1 = torch.ShortTensor(3,2,4)
print(tensor1.dtype)
tensor2 = torch.tensor([1,2,3],dtype=torch.short)
print(tensor2.dtype)

torch.int16
torch.int16


# 按照指定区间的张量创建


In [19]:
tensor1 = torch.arange(0,10,2)
print(tensor1)

tensor([0, 2, 4, 6, 8])


In [21]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [22]:
torch.logspace(0,10,5)

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])

# 按照数值填充


In [23]:
tensor1 = torch.zeros(2, 3)
print(tensor1)
print(tensor1.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [24]:
tensor2 = torch.ones_like(tensor1)
print(tensor2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [25]:
tensor1 = torch.full((3,2), 6.5)
print(tensor1)
print(tensor1.dtype)

tensor([[6.5000, 6.5000],
        [6.5000, 6.5000],
        [6.5000, 6.5000]])
torch.float32


In [26]:
tensor2 = torch.empty_like(tensor1)
print(tensor2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [27]:
tensor1 = torch.eye(3)
print(tensor1)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [28]:
tensor1 = torch.eye(3, 5)
print(tensor1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


# 随机的张量创建


In [29]:
tensor1 = torch.rand(2, 3)
print(tensor1)

tensor([[0.7681, 0.6126, 0.1948],
        [0.0055, 0.9325, 0.7815]])


In [30]:
tensor2 = torch.rand_like(tensor1)
print(tensor2)

tensor([[0.9727, 0.6859, 0.1967],
        [0.6817, 0.3582, 0.2434]])


In [31]:
tensor1 = torch.randint(low=0, high=100, size=(2, 3))
print(tensor1)

tensor([[73, 88, 35],
        [29,  7, 52]])


In [32]:
tensor2 = torch.randint_like(tensor1, low=10, high=20)
print(tensor2)

tensor([[10, 16, 13],
        [19, 13, 13]])


In [33]:
tensor1 = torch.randn(4, 2)
print(tensor1)

tensor([[ 1.3985, -0.8727],
        [ 0.6765, -0.9905],
        [-0.2783,  0.6378],
        [-0.2929,  0.3725]])


In [34]:
tensor2 = torch.randn_like(tensor1)
print(tensor2)

tensor([[ 1.3149, -1.2089],
        [ 1.2507, -0.7879],
        [-0.0987, -0.0189],
        [ 2.0847, -1.2324]])


In [35]:
tensor1 = torch.normal(5, 2, tensor2.shape)
print(tensor1)

tensor([[6.5975, 6.0659],
        [6.0557, 6.5381],
        [7.3064, 4.9770],
        [7.0170, 1.9145]])


In [36]:
# 随机重新排列
tensor1 = torch.randperm(10)
print(tensor1)

tensor([3, 8, 2, 1, 7, 9, 6, 5, 0, 4])


In [37]:
# 查看和指定随机数种子
print(torch.random.initial_seed())

1878269954977979925


In [38]:
torch.manual_seed(42)

In [39]:
print(torch.random.initial_seed())

42
