In [3]:
import torch

# 张量的基本创建  按照内容创建张量

In [7]:
#传入一个标量
tensor1 = torch.tensor(10)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor(10)
torch.Size([])
torch.int64


In [8]:
#传入一个数组
tensor1 = torch.tensor([1,2,3])
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([1, 2, 3])
torch.Size([3])
torch.int64


In [9]:
# 传入一个二维 nd.array
import numpy as np
tensor3 = torch.tensor(np.array([[1,2,3],[4,5,6]]))
print(tensor3)
print(tensor3.size())
print(tensor3.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


# 创建指定形状的张量


In [12]:
tensor1 = torch.Tensor(3,2,4)
print(tensor1)
print(tensor1.size())
print(tensor1.dtype)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([3, 2, 4])
torch.float32


In [13]:
tensor2 = torch.Tensor(np.array([[1,2,3],[4,5,6]]))
print(tensor2)
print(tensor2.size())
print(tensor2.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.float32


# 创建指定类型的张量


In [14]:
tensor1 = torch.IntTensor(3,2,4)
print(tensor1.dtype)
tensor2 = torch.tensor([1,2,3])
print(tensor2.dtype)


torch.int32
torch.int64


In [18]:
tensor1 = torch.ShortTensor(3,2,4)
print(tensor1.dtype)
tensor2 = torch.tensor([1,2,3],dtype=torch.short)
print(tensor2.dtype)

torch.int16
torch.int16
